on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

name: 🏗️ Deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout 
        uses: actions/checkout@v4

      - name: 🧰 Build
        uses: withastro/action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 🚀 Upload
        uses: actions/deploy-pages@v4
